export const colors = {
  caution: '#FFD700',
  critical: '#FF6363',
  header_BackgroundColor: '#0b262eF2',
  header_TintColor: '#FDFFFC',
  input_BackgroundColor: '#FDFFFC0D',
  input_BorderColor: '#434D5680',
  input_FocusedBackgroundColor: '#FDFFFC26',
  input_FocusedBorderColor: '#434D5640',
  input_placeholderTextColor: '#FDFFFC4D',
  positive: '#32CD32',
  primary_TintColor: '#0bffff',
  primary_TintColor_subtle: '#0bffff59',
  screen_BackgroundColor: '#0b262e',
  screen_BackgroundColor_subtle: '#0b262eF2',
  secondary_TintColor: '#7fffd4',
  secondary_TintColor_subtle: '#0bffff59',
  statusBar_BackgroundColor: '#0b262e',
  statusBar_TintColor: '#FDFFFC',
  tabBar_ActiveTintColor: '#0bffff',
  tabBar_BackgroundColor: '#0b262e',
  tabBar_BorderColor: '#0bffff59',
  tabBar_InactiveTintColor: '#0bffff59',
  text_primary: '#FDFFFC',
  text_primary_subtle: '#FDFFFC4D',
  text_secondary: '#434D56',
  text_secondary_subtle: '#434D5640',
};
